------------------------
-- SCL - Projet n°1
------------------------


-- ------------------------
-- DROP TRIGGERS
-- ------------------------
DROP TRIGGER TR_METEO;
DROP TRIGGER TR_STATION;
DROP TRIGGER TR_PAYS;

-- ------------------------
-- DROP TABLES
-- ------------------------
DROP TABLE METEO;
DROP TABLE STATION;
DROP TABLE PAYS;

-- ------------------------
-- DROP SEQUENCES
-- ------------------------
DROP SEQUENCE SEQ_METEO;
DROP SEQUENCE SEQ_STATION;
DROP SEQUENCE SEQ_PAYS;



CREATE SEQUENCE SEQ_PAYS;

CREATE TABLE PAYS (
                      NUMERO NUMBER (20) CONSTRAINT PK_PAYS PRIMARY KEY,
                      NOM VARCHAR2(30) CONSTRAINT UK_PAYS_NAME UNIQUE,
                      CODE VARCHAR2 (20) CONSTRAINT UK_PAYS_CODE UNIQUE
);

CREATE OR REPLACE TRIGGER TR_PAYS BEFORE INSERT ON PAYS FOR EACH ROW
BEGIN
    :NEW.NUMERO := SEQ_PAYS.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_STATION;

CREATE TABLE STATION (
                         numero NUMBER(20) CONSTRAINT PK_STATION PRIMARY KEY,
                         ID_STATION VARCHAR2(20) CONSTRAINT UK_ID_STATION UNIQUE,
                         TIME_ZONE NUMBER(10),
                         LATITUDE NUMBER(10,2),
                         LONGITUDE NUMBER(10,2),
                         NOM VARCHAR2 (50),
                         NUM_PAYS NUMBER(20),
                         CONSTRAINT FK_STATION_PAYS FOREIGN KEY (NUM_PAYS) REFERENCES PAYS(NUMERO),
                         CONSTRAINT CK_LATITUDE_STATION CHECK (LATITUDE >= -90 AND LATITUDE <= 90),
                         CONSTRAINT CK_LONGITUDE_STATION CHECK (LONGITUDE >= -180 AND LONGITUDE <= 180)
);

CREATE OR REPLACE TRIGGER TR_STATION BEFORE INSERT ON STATION FOR EACH ROW
BEGIN
		:NEW.NUMERO := SEQ_STATION.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_METEO;

CREATE TABLE METEO (
                       NUMERO NUMBER(20) CONSTRAINT PK_METEO PRIMARY KEY,
                       DESCRIPTION VARCHAR2(50),
                       DATE_MESURE DATE,
                       TEMPERATURE NUMBER(6,2),
                       TEMP_RESSENTI NUMBER(6,2),
                       PRESSION NUMBER(4),
                       HUMIDITE NUMBER(6,2),
                       VENT_VITESSE NUMBER(6,2),
                       VENT_ORIENTATION NUMBER(6,2),
                       ICON VARCHAR2 (50),
                       NUM_STATION NUMBER (20),
                       CONSTRAINT UK_METEO_NUM_DATE UNIQUE (NUM_STATION, DATE_MESURE),
                       CONSTRAINT FK_METEO_STATION FOREIGN KEY(NUM_STATION) REFERENCES STATION(NUMERO)
);

CREATE TRIGGER TR_METEO BEFORE INSERT ON METEO FOR EACH ROW
BEGIN
    :NEW.NUMERO := SEQ_METEO.NEXTVAL;
END;
/

---------------
--index
---------------
CREATE INDEX IDX_STATION_PAYS ON STATION(NUM_PAYS);
CREATE INDEX IDX_METEO_STATION ON METEO(NUM_STATION);
